const schema = require('./schema.js');



var Applicants = {
    demo1: Object.assign(
    JSON.parse(JSON.stringify(schema.newApplicant)), 
  { id: null,
    username: 'bobs',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    firstName: 'Bobs',
    lastName: 'UpAndDownInTheWater',
    email: 'bobs@gmail.com',
    phone_number: '(123)456-7890',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    profile_pic_url: 'http://res.cloudinary.com/dse6qhxk5/image/upload/v1493339302/dale_ki3o5c.jpg',
  }),
    demo2: Object.assign(
    JSON.parse(JSON.stringify(schema.newApplicant)), 
  { id: null,
    username: 'marks',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    firstName: 'Marks',
    lastName: 'OnYourShirt',
    email: 'marks@gmail.com',
    phone_number: '(123)456-7891',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    profile_pic_url: 'http://res.cloudinary.com/dse6qhxk5/image/upload/v1493339302/gabe_ynpexk.jpg',
  }),
    demo3: Object.assign(
    JSON.parse(JSON.stringify(schema.newApplicant)), 
  { id: null,
    username: 'toms',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    firstName: 'Toms',
    lastName: 'Peeping',
    email: 'toms@gmail.com',
    phone_number: '(123)456-7892',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    profile_pic_url: 'http://res.cloudinary.com/dse6qhxk5/image/upload/v1493310538/arpom4b0wqekpfqrnjn1.jpg',
  }),
    demo4: Object.assign(
    JSON.parse(JSON.stringify(schema.newApplicant)), 
  { id: null,
    username: 'ace_coder',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    firstName: 'Ace',
    lastName: 'Coder',
    email: 'ac@gmail.com',
    phone_number: '(233)456-7232',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    profile_pic_url: 'http://res.cloudinary.com/dse6qhxk5/image/upload/v1493148143/a1jqk6hgsjpigta9zp2k.jpg',
  }),
    demo5: Object.assign(
    JSON.parse(JSON.stringify(schema.newApplicant)), 
  { id: null,
    username: 'billy_best',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    firstName: 'Billy',
    lastName: 'Best',
    email: 'Billy@gmail.com',
    phone_number: '(223)446-4592',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    profile_pic_url: 'http://res.cloudinary.com/dse6qhxk5/image/upload/v1493310538/arpom4b0wqekpfqrnjn1.jpg',
  }),
    demo7: Object.assign(
    JSON.parse(JSON.stringify(schema.newApplicant)), 
  { id: null,
    username: 'lookingJust',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    firstName: 'Just',
    lastName: 'Looking',
    email: 'jl@gmail.com',
    phone_number: '(122)123-3892',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    profile_pic_url: 'http://res.cloudinary.com/dse6qhxk5/image/upload/v1493339302/dale_ki3o5c.jpg',
  }),
    demo8: Object.assign(
    JSON.parse(JSON.stringify(schema.newApplicant)), 
  { id: null,
    username: 'l33t',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    firstName: 'L33t',
    lastName: 'COder',
    email: 'LC@gmail.com',
    phone_number: '(133)126-7392',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    profile_pic_url: 'http://res.cloudinary.com/dse6qhxk5/image/upload/v1493339302/gabe_ynpexk.jpg',
  }),
    demo8: Object.assign(
    JSON.parse(JSON.stringify(schema.newApplicant)), 
  { id: null,
    username: 'developer_dude',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    firstName: 'Dev',
    lastName: 'Dude',
    email: 'ddude@hotmail.com',
    phone_number: '(123)456-2393',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    profile_pic_url: 'http://res.cloudinary.com/dse6qhxk5/image/upload/v1493148143/a1jqk6hgsjpigta9zp2k.jpg',
  }),
    demo10: Object.assign(
    JSON.parse(JSON.stringify(schema.newApplicant)), 
  { id: null,
    username: 'init2winit',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    firstName: 'Init',
    lastName: 'Winit',
    email: 'Iwinit@msn.com',
    phone_number: '(223)256-4432',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    profile_pic_url: 'http://res.cloudinary.com/dse6qhxk5/image/upload/v1493148143/a1jqk6hgsjpigta9zp2k.jpg',
  }),
    demo10: Object.assign(
    JSON.parse(JSON.stringify(schema.newApplicant)), 
  { id: null,
    username: 'jsmith',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    firstName: 'John',
    lastName: 'Smith',
    email: 'jsmith10928490@gmail.com',
    phone_number: '(122)113-1112',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    profile_pic_url: 'http://res.cloudinary.com/dse6qhxk5/image/upload/v1493310538/arpom4b0wqekpfqrnjn1.jpg',
  }),
    demo12: Object.assign(
    JSON.parse(JSON.stringify(schema.newApplicant)), 
  { id: null,
    username: 'nqueens',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    firstName: 'Enn',
    lastName: 'Queenz',
    email: 'toughAlgs@gmail.com',
    phone_number: '(923)226-1231',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    profile_pic_url: 'http://res.cloudinary.com/dse6qhxk5/image/upload/v1493339302/gabe_ynpexk.jpg',
  }),
}


var Employer = {
    demo1: Object.assign(
    JSON.parse(JSON.stringify(schema.newEmployer)),
  { id: null,
    username: 'hackreactor',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    company_name: 'Hack Reactor',
    email: 'awesome@hackreactor.com',
    phone_number: '(987)654-3210',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    logo_url: 'https://res.cloudinary.com/dse6qhxk5/image/upload/v1493338548/hacz9nec5ih7qezbt4kk.jpg',
    job_postings_id: null 
    }),
    demo2: Object.assign(
    JSON.parse(JSON.stringify(schema.newEmployer)),
  { id: null,
    username: 'apple',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    company_name: 'apple',
    email: 'apple@apple.com',
    phone_number: '(650)650-6500',
    city: 'Cupertino',
    state: 'CA',
    country: 'USA',
    logo_url: 'https://res.cloudinary.com/dse6qhxk5/image/upload/v1493338548/hacz9nec5ih7qezbt4kk.jpg',
    job_postings_id: null 
    }),
    demo3: Object.assign(
    JSON.parse(JSON.stringify(schema.newEmployer)),
  { id: null,
    username: 'facebook',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    company_name: 'facebook',
    email: 'facebook@facebook.com',
    phone_number: '(654)655-6504',
    city: 'San Fernando',
    state: 'CA',
    country: 'USA',
    logo_url: 'https://res.cloudinary.com/dse6qhxk5/image/upload/v1493338548/hacz9nec5ih7qezbt4kk.jpg',
    job_postings_id: null 
    }),
    demo4: Object.assign(
    JSON.parse(JSON.stringify(schema.newEmployer)),
  { id: null,
    username: 'bmw',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    company_name: 'bmwUSA',
    email: 'bmw_USA@bmw.com',
    phone_number: '(634)755-6204',
    city: 'LA',
    state: 'CA',
    country: 'USA',
    logo_url: 'https://res.cloudinary.com/dse6qhxk5/image/upload/v1493338548/hacz9nec5ih7qezbt4kk.jpg',
    job_postings_id: null 
    }),
    demo5: Object.assign(
    JSON.parse(JSON.stringify(schema.newEmployer)),
  { id: null,
    username: 'AirBnB',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    company_name: 'AirBnB@airbnb.com',
    phone_number: '(221)233-2304',
    city: 'New York City',
    state: 'NY',
    country: 'USA',
    logo_url: 'https://res.cloudinary.com/dse6qhxk5/image/upload/v1493338548/hacz9nec5ih7qezbt4kk.jpg',
    job_postings_id: null 
    }),
    demo6: Object.assign(
    JSON.parse(JSON.stringify(schema.newEmployer)),
  { id: null,
    username: 'Uber',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    company_name: 'uber',
    email: 'uber1@uber.com',
    phone_number: '(221)105-6504',
    city: 'Sacramento',
    state: 'CA',
    country: 'USA',
    logo_url: 'https://res.cloudinary.com/dse6qhxk5/image/upload/v1493338548/hacz9nec5ih7qezbt4kk.jpg',
    job_postings_id: null 
    }),
    demo7: Object.assign(
    JSON.parse(JSON.stringify(schema.newEmployer)),
  { id: null,
    username: 'united',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    company_name: 'unitedAir',
    email: 'unitedair@unitedair.com',
    phone_number: '(654)655-6504',
    city: 'San Diego',
    state: 'CA',
    country: 'USA',
    logo_url: 'https://res.cloudinary.com/dse6qhxk5/image/upload/v1493338548/hacz9nec5ih7qezbt4kk.jpg',
    job_postings_id: null 
    }),
    demo8: Object.assign(
    JSON.parse(JSON.stringify(schema.newEmployer)),
  { id: null,
    username: 'Nintendo',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    company_name: 'nintendo',
    email: 'nintendo111@nintendo.com',
    phone_number: '(111)111-1111',
    city: 'Las Vegas',
    state: 'NV',
    country: 'USA',
    logo_url: 'https://res.cloudinary.com/dse6qhxk5/image/upload/v1493338548/hacz9nec5ih7qezbt4kk.jpg',
    job_postings_id: null 
    }),
    demo9: Object.assign(
    JSON.parse(JSON.stringify(schema.newEmployer)),
  { id: null,
    username: 'Jeep',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    company_name: 'jeep',
    email: 'jeep@jeepcom',
    phone_number: '(442)121-3248',
    city: 'Boulder',
    state: 'CO',
    country: 'USA',
    logo_url: 'https://res.cloudinary.com/dse6qhxk5/image/upload/v1493338548/hacz9nec5ih7qezbt4kk.jpg',
    job_postings_id: null 
    }),
    demo10: Object.assign(
    JSON.parse(JSON.stringify(schema.newEmployer)),
  { id: null,
    username: 'Microsoft',
    password: '$2a$10$h8sw.jt81MP/AlhpBHgtUu/84kAHw.Cg0ACZIGbNn/CQCUSbshzOK',
    company_name: 'microsoft',
    email: 'microsoft@microsoft.com',
    phone_number: '(123)331-1359',
    city: 'Miami',
    state: 'FL',
    country: 'USA',
    logo_url: 'https://res.cloudinary.com/dse6qhxk5/image/upload/v1493338548/hacz9nec5ih7qezbt4kk.jpg',
    job_postings_id: null 
    }),

}

var JobPost = {
    demo1: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 1,
  },
    demo2: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 2,
  },
    demo3: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 3,
  },
    demo4: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 4,
  },
    demo5: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 5,
  },
    demo6: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 6,
  },
    demo7: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 7,
  },
    demo8: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 7,
  },
    demo9: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 8,
  },
    demo10: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 10,
  },
    demo11: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 10,
  },
    demo12: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 10,
  },
    demo13: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 2,
  },
    demo14: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 2,
  },
    demo15: {
    id: null,
    position: 'software engineer',
    description: 'React, databases, Jquery, HTML, etc...',
    location: 'SF',
    salary: 115000,
    post_date: null,
    employer_id: 3,
  },
}


exports.Resume = Object.assign(
  JSON.parse(JSON.stringify(schema.newApplicantFile)),
  { id: null,
    url: 'https://res.cloudinary.com/dse6qhxk5/image/upload/v1493339062/mdkwkyfdfgctubkvfiq2.jpg',
    type: 'resume',
    applicant_id: 3,
  });


exports.CoverLetter = Object.assign(
  JSON.parse(JSON.stringify(schema.newApplicantFile)),
  { id: null,
    url: 'https://res.cloudinary.com/dse6qhxk5/image/upload/v1493339062/mdkwkyfdfgctubkvfiq2.jpg',
    type: 'coverletter',
    applicant_id: 3,
  });

exports.JobPost1 = Object.assign(
  JSON.parse(JSON.stringify(schema.newApplicantFile)),
  { id: null,
    url: 'https://res.cloudinary.com/dse6qhxk5/image/upload/v1493339062/mdkwkyfdfgctubkvfiq2.jpg',
    type: 'coverletter',
    applicant_id: 3,
  });

exports.applicants = Object.values(Applicants);
exports.employer = Object.values(Employer);
exports.jobPost = Object.values(JobPost);

